# Generated by Django 2.2.4 on 2019-11-05 09:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('clicked', models.IntegerField(default=0)),
                ('when', models.DateTimeField(default=datetime.date(2019, 11, 5))),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('clicked', models.IntegerField(default=0)),
                ('when', models.DateTimeField(default=datetime.date(2019, 11, 5))),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('favorite', models.CharField(default='00', max_length=500)),
                ('when', models.DateTimeField(default=datetime.date(2019, 11, 5))),
                ('latestView', models.CharField(default='', max_length=10)),
                ('mychat', models.CharField(default=',', max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief', models.TextField()),
                ('target', models.TextField()),
                ('criteria', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('supply_way', models.TextField(blank=True, null=True)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('clicked', models.IntegerField(default=0)),
                ('doing_users', models.ManyToManyField(blank=True, related_name='doing_policies', to=settings.AUTH_USER_MODEL)),
                ('pick_users', models.ManyToManyField(blank=True, related_name='pick_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('edit', models.BooleanField(default=False)),
                ('when', models.DateTimeField(default=datetime.date(2019, 11, 5))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Notice')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('edit', models.BooleanField(default=False)),
                ('when', models.DateTimeField(default=datetime.date(2019, 11, 5))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Board')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
