# Generated by Django 2.2.4 on 2019-11-03 02:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='doing_users',
            field=models.ManyToManyField(related_name='doing_pick_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 11, 3)),
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 11, 3)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 11, 3)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 11, 3)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 11, 3)),
        ),
    ]
