# Generated by Django 2.2.4 on 2019-10-30 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 10, 30)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='when',
            field=models.DateTimeField(default=datetime.date(2019, 10, 30)),
        ),
    ]
