# Generated by Django 2.2.4 on 2019-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191030_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='when',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='when',
            field=models.TextField(),
        ),
    ]
