# Generated by Django 2.2.4 on 2019-11-03 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191103_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='doing_users',
            field=models.ManyToManyField(blank=True, related_name='doing_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
