# Generated by Django 2.2.4 on 2019-10-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191023_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
